name: super_app_flutter_monorepo
description: Mono repository of super_app_flutter_monorepo flutter projects.
publish_to: 'none' # Remove this line if you wish to publish to pub.devss

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  melos: ^6.3.2

